//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManager.SizeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SizeServiceReference.ISizeService")]
    public interface ISizeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISizeService/GetSizeInfo", ReplyAction="http://tempuri.org/ISizeService/GetSizeInfoResponse")]
        string GetSizeInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISizeService/GetSizeInfo", ReplyAction="http://tempuri.org/ISizeService/GetSizeInfoResponse")]
        System.Threading.Tasks.Task<string> GetSizeInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISizeService/GetSizeInfoForMonth", ReplyAction="http://tempuri.org/ISizeService/GetSizeInfoForMonthResponse")]
        string GetSizeInfoForMonth(int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISizeService/GetSizeInfoForMonth", ReplyAction="http://tempuri.org/ISizeService/GetSizeInfoForMonthResponse")]
        System.Threading.Tasks.Task<string> GetSizeInfoForMonthAsync(int month);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISizeServiceChannel : ClientManager.SizeServiceReference.ISizeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SizeServiceClient : System.ServiceModel.ClientBase<ClientManager.SizeServiceReference.ISizeService>, ClientManager.SizeServiceReference.ISizeService {
        
        public SizeServiceClient() {
        }
        
        public SizeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SizeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SizeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SizeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetSizeInfo() {
            return base.Channel.GetSizeInfo();
        }
        
        public System.Threading.Tasks.Task<string> GetSizeInfoAsync() {
            return base.Channel.GetSizeInfoAsync();
        }
        
        public string GetSizeInfoForMonth(int month) {
            return base.Channel.GetSizeInfoForMonth(month);
        }
        
        public System.Threading.Tasks.Task<string> GetSizeInfoForMonthAsync(int month) {
            return base.Channel.GetSizeInfoForMonthAsync(month);
        }
    }
}
